### ISSUE TITLE
Incompatible matrix dimensions error

### ISSUE THREAD

**Issue by Glfrey** [adigorla/PACA#1]
Hello,

I'm trying to run PACA on my data, which is set up as specified (samples x features) and I'm receiving the following error:

```
> autoPACA(case_data_trans, control_data_trans)
Starting doRCCA ...
Error: cov(): incompatible matrix dimensions: 880x34359738478 and 51539607662x1320
```
However, my data is nowhere near this large:

```
> dim(case_data_trans)
[1]   8 110
> dim(control_data_trans)
[1]  12 110

```

Could you please advise on what's causing this issue?

Many thanks

**Comment by adigorla** [comment]
Hi! Apologies for the delay, but I'm excited to share that the PACA package has undergone a major update. It's now fully implemented in C++ using the Eigen library, offering significantly improved numerical stability and a performance boost of 10-100x.

Regarding the issue you raised, it looks like your input matrix has the shape [samples, features]. The PACA package expects the input matrix to be transposed to [features, samples], where the features are aligned correctly between matrices.

I've clarified this requirement in the [README](https://github.com/adigorla/PACA/blob/cb1cb93dd3b271234da1b596d614ab7cd1014dcb/README.md) and added data integrity checks to the code to raise an error if the input format doesn't meet the expected structure.
