### ISSUE TITLE
Problem with PACA installation

### ISSUE THREAD

**Issue by ShangLiii** [adigorla/PACA#2]
Hi I have tried to install PACA to R/4.4.0 using the command "devtools::install_github("adigorla/PACA")" but failed.
The error was written as:
"Error: package or namespace load failed for ‘PACA’ in namespaceExport(ns, exports):
 undefined exports: rpaca_old"
![image](https://github.com/user-attachments/assets/b806b799-f7d5-441a-9a43-a884d1fdd3e9)

Any idea what is the problem and how to fix this?
Thanks!

**Comment by adigorla** [comment]
Sorry about that, roxygen2 didnt seem to propagate a major change I made to the rpaca module all the way to the NAMESPACE file.  Commit [cb1cb93](https://github.com/adigorla/PACA/commit/cb1cb93dd3b271234da1b596d614ab7cd1014dcb) should fix this issue!
